server:
  port: 9004

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        # 换成nginx反向代理的地址端口8849 做集群
        server-addr: 192.168.136.131:8849 #集群配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'




