server:
  port: 80


spring:
  application:
    name: cloud-order-consumer
  #cloud-zookeeper注册中心
  cloud:
    zookeeper:
      connect-string: 192.168.136.131:2181,192.168.136.132:2181,192.168.136.133:2181
